In [1]:
import torch
import numpy as np

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

In [2]:
y = torch.rand(3,4,5)
y

tensor([[[0.2080, 0.6711, 0.8618, 0.9985, 0.9718],
         [0.8867, 0.8121, 0.3336, 0.3416, 0.0715],
         [0.5436, 0.5743, 0.6416, 0.8343, 0.8963],
         [0.0960, 0.1707, 0.9128, 0.6986, 0.0232]],

        [[0.4307, 0.1068, 0.7849, 0.6666, 0.6911],
         [0.8742, 0.1620, 0.4698, 0.4370, 0.2504],
         [0.9323, 0.8253, 0.3815, 0.6575, 0.7341],
         [0.2089, 0.4397, 0.5815, 0.8620, 0.3045]],

        [[0.5410, 0.4438, 0.1973, 0.7701, 0.3347],
         [0.1303, 0.3731, 0.7544, 0.0180, 0.6791],
         [0.0452, 0.2064, 0.3004, 0.4050, 0.1065],
         [0.6178, 0.3815, 0.8968, 0.5550, 0.1107]]])

In [3]:
y.type()

'torch.FloatTensor'

In [4]:
# Выведите его форму (shape)
y.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6 X 10
y1 = y.reshape([6,10])
y1

tensor([[0.2080, 0.6711, 0.8618, 0.9985, 0.9718, 0.8867, 0.8121, 0.3336, 0.3416,
         0.0715],
        [0.5436, 0.5743, 0.6416, 0.8343, 0.8963, 0.0960, 0.1707, 0.9128, 0.6986,
         0.0232],
        [0.4307, 0.1068, 0.7849, 0.6666, 0.6911, 0.8742, 0.1620, 0.4698, 0.4370,
         0.2504],
        [0.9323, 0.8253, 0.3815, 0.6575, 0.7341, 0.2089, 0.4397, 0.5815, 0.8620,
         0.3045],
        [0.5410, 0.4438, 0.1973, 0.7701, 0.3347, 0.1303, 0.3731, 0.7544, 0.0180,
         0.6791],
        [0.0452, 0.2064, 0.3004, 0.4050, 0.1065, 0.6178, 0.3815, 0.8968, 0.5550,
         0.1107]])

In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y2 = y1 * torch.Tensor ([1, 4, 2, 2, 1, 1, 4, 2, 2, 1])
y2


tensor([[0.2080, 2.6843, 1.7236, 1.9970, 0.9718, 0.8867, 3.2483, 0.6673, 0.6832,
         0.0715],
        [0.5436, 2.2972, 1.2831, 1.6686, 0.8963, 0.0960, 0.6828, 1.8257, 1.3971,
         0.0232],
        [0.4307, 0.4271, 1.5698, 1.3332, 0.6911, 0.8742, 0.6480, 0.9396, 0.8740,
         0.2504],
        [0.9323, 3.3011, 0.7630, 1.3149, 0.7341, 0.2089, 1.7588, 1.1630, 1.7240,
         0.3045],
        [0.5410, 1.7753, 0.3945, 1.5403, 0.3347, 0.1303, 1.4923, 1.5087, 0.0360,
         0.6791],
        [0.0452, 0.8256, 0.6009, 0.8100, 0.1065, 0.6178, 1.5261, 1.7936, 1.1099,
         0.1107]])

In [7]:
y22 = y * torch.Tensor([1, 4, 2, 2, 1] )
y22

tensor([[[0.2080, 2.6843, 1.7236, 1.9970, 0.9718],
         [0.8867, 3.2483, 0.6673, 0.6832, 0.0715],
         [0.5436, 2.2972, 1.2831, 1.6686, 0.8963],
         [0.0960, 0.6828, 1.8257, 1.3971, 0.0232]],

        [[0.4307, 0.4271, 1.5698, 1.3332, 0.6911],
         [0.8742, 0.6480, 0.9396, 0.8740, 0.2504],
         [0.9323, 3.3011, 0.7630, 1.3149, 0.7341],
         [0.2089, 1.7588, 1.1630, 1.7240, 0.3045]],

        [[0.5410, 1.7753, 0.3945, 1.5403, 0.3347],
         [0.1303, 1.4923, 1.5087, 0.0360, 0.6791],
         [0.0452, 0.8256, 0.6009, 0.8100, 0.1065],
         [0.6178, 1.5261, 1.7936, 1.1099, 0.1107]]])

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
y3 = y2 @ torch.transpose(y2,0,1)
y3

tensor([[27.4072, 17.1718, 11.3978, 21.5836, 15.0021, 12.4504],
        [17.1718, 16.5677,  9.5421, 17.6811, 11.6005, 10.0681],
        [11.3978,  9.5421,  7.9808,  9.2676,  6.5952,  6.6807],
        [21.5836, 17.6811,  9.2676, 22.1712, 13.6122, 11.2154],
        [15.0021, 11.6005,  6.5952, 13.6122, 11.0671,  8.1895],
        [12.4504, 10.0681,  6.6807, 11.2154,  8.1895,  8.8840]])

In [9]:
y3 = y2 @ y2.T
y3

tensor([[27.4072, 17.1718, 11.3978, 21.5836, 15.0021, 12.4504],
        [17.1718, 16.5677,  9.5421, 17.6811, 11.6005, 10.0681],
        [11.3978,  9.5421,  7.9808,  9.2676,  6.5952,  6.6807],
        [21.5836, 17.6811,  9.2676, 22.1712, 13.6122, 11.2154],
        [15.0021, 11.6005,  6.5952, 13.6122, 11.0671,  8.1895],
        [12.4504, 10.0681,  6.6807, 11.2154,  8.1895,  8.8840]])

In [13]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable


In [23]:
x = Variable(torch.Tensor([1.]), requires_grad = True)
z = Variable(torch.Tensor([0.5]), requires_grad = True)
t = Variable(torch.Tensor([2.]), requires_grad = True)
y = x**3 + z - 75*t

In [24]:
y.backward()

In [25]:
x.grad,z.grad,t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [27]:
# Создайте единичный тензор размера 5x6
x1 = torch.ones([5,6])
x1

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [28]:
# Переведите его в формат numpy
x2 = x1.numpy()
x2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [148]:
from torch import nn 
from torch import optim

In [243]:
linear = nn.Linear(3, 3)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.0949,  0.4834,  0.4833],
        [ 0.2409, -0.3735,  0.3468],
        [ 0.0575,  0.4902, -0.4259]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4142,  0.2568, -0.3520], requires_grad=True)


In [244]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.001)

In [245]:
x = Variable(torch.randn(3), requires_grad = True)
y = x**linear.weight - 2 * x**2 + 5

In [246]:
optimizer.zero_grad()
pred = linear(x)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  15.553821563720703


In [247]:
loss.backward()

In [248]:
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.8429, -0.8415, -0.6359],
        [-4.8588, -2.8966, -3.0437],
        [-4.8208, -1.7908, -3.0172]])
dL/db:  tensor([-0.6022, -3.2040, -3.1688])


In [249]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.0949,  0.4834,  0.4833],
        [ 0.2409, -0.3735,  0.3468],
        [ 0.0575,  0.4902, -0.4259]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4142,  0.2568, -0.3520], requires_grad=True)


In [250]:
optimizer.step()
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.0957,  0.4843,  0.4839],
        [ 0.2457, -0.3706,  0.3499],
        [ 0.0624,  0.4920, -0.4229]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4136,  0.2601, -0.3489], requires_grad=True)


In [251]:
optimizer.step()
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.0966,  0.4851,  0.4845],
        [ 0.2506, -0.3677,  0.3529],
        [ 0.0672,  0.4938, -0.4199]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4130,  0.2633, -0.3457], requires_grad=True)


In [252]:
optimizer.step()
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.0974,  0.4860,  0.4852],
        [ 0.2555, -0.3648,  0.3560],
        [ 0.0720,  0.4956, -0.4168]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4124,  0.2665, -0.3425], requires_grad=True)
